<?php

namespace TrainingZoneBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use TrainingZoneBundle\Entity\Training;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository {


    public function getTrainingByCategory($catId) {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT t FROM TrainingZoneBundle:Training t LEFT JOIN t.categories c WHERE c.id = :catId ");
        $query->setParameter("catId", $catId);
        $allTrainings = $query->getResult();
        return ['allTrainings' => $allTrainings];
    }

}
